name: PlanetFxServerSystems
version: 1.0.8
author: Sebastian Mikolai

main: de.SebastianMikolai.PlanetFx.ServerSystem.SSClient.SSClient

commands:
  lobby:
    description: Back tp Lobby
    usage: /lobby