name: PlanetFxServerSystems
version: 2.1
author: Sebastian Mikolai

main: de.SebastianMikolai.PlanetFx.ServerSystem.SSClient.SSClient

commands:
  lobby:
    description: Back to Lobby
    usage: /lobby